-- Adminer 4.8.1 PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) dump

DROP TABLE IF EXISTS "banks";
DROP SEQUENCE IF EXISTS banks_id_seq;
CREATE SEQUENCE banks_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."banks" (
    "id" integer DEFAULT nextval('banks_id_seq') NOT NULL,
    "rus" character(255) NOT NULL,
    "eng" character(255) NOT NULL,
    CONSTRAINT "banks_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "banks" ("id", "rus", "eng") VALUES
(0,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	'Sberbank                                                                                                                                                                                                                                                       '),
(10,	'🟡 Тинькофф                                                                                                                                                                                                                                                     ',	'Tinkoff                                                                                                                                                                                                                                                        '),
(2,	'🟣 СБП                                                                                                                                                                                                                                                          ',	'SBP - Fast Bank Transfer                                                                                                                                                                                                                                       '),
(3,	'🟠 Райффайзенбанк                                                                                                                                                                                                                                               ',	'Raiffeisenbank                                                                                                                                                                                                                                                 '),
(4,	'🔴 Альфа банк                                                                                                                                                                                                                                                   ',	'Alfa-bank                                                                                                                                                                                                                                                      '),
(7,	'⚪️ Другие банки                                                                                                                                                                                                                                                ',	'another                                                                                                                                                                                                                                                        '),
(6,	'🟩 USDT                                                                                                                                                                                                                                                         ',	'USDT                                                                                                                                                                                                                                                           '),
(5,	'💵 Наличные                                                                                                                                                                                                                                                     ',	'cash                                                                                                                                                                                                                                                           ');

DROP TABLE IF EXISTS "orders";
DROP SEQUENCE IF EXISTS orders_id_seq;
CREATE SEQUENCE orders_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."orders" (
    "id" integer DEFAULT nextval('orders_id_seq') NOT NULL,
    "username" character(255) NOT NULL,
    "admin_pay" real NOT NULL,
    "user_pay" real NOT NULL,
    "course_rub" real NOT NULL,
    "course_thb" real NOT NULL,
    "marje" real NOT NULL,
    "trade_method" character(255) NOT NULL,
    "gain" real NOT NULL,
    "review" text,
    "mark" integer,
    "completed" character(255) NOT NULL,
    "date" timestamp,
    "ids" character(255),
    "user_bat" real,
    "user_usdt" real,
    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "orders" ("id", "username", "admin_pay", "user_pay", "course_rub", "course_thb", "marje", "trade_method", "gain", "review", "mark", "completed", "date", "ids", "user_bat", "user_usdt") VALUES
(7,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52282.99,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1103.21,	NULL,	NULL,	'cancle                                                                                                                                                                                                                                                         ',	'2024-01-23 22:55:49.917205',	'c4f2287d-a587-47f9-bd13-ca1b69ea5b9c                                                                                                                                                                                                                           ',	20000,	10),
(5,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52282.99,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1103.21,	NULL,	NULL,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-23 22:49:42.312969',	'b1eec114-6bd1-435a-b467-ac0d02d31836                                                                                                                                                                                                                           ',	20000,	10),
(9,	'ssk1722                                                                                                                                                                                                                                                        ',	25589.89,	26617.16,	35,	283.71,	1.01,	'🟡Тинькофф                                                                                                                                                                                                                                                      ',	1027.27,	NULL,	NULL,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-23 22:57:30.89173',	'2b0a4de6-124b-4d9a-b88e-0a4bb2de6765                                                                                                                                                                                                                           ',	10000,	10),
(4,	'ssk1722                                                                                                                                                                                                                                                        ',	12794.94,	13080.78,	35,	141.85,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	285.84,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-23 22:35:23.99666',	'87b5dc55-e3d9-4119-a719-fb3b47d741eb                                                                                                                                                                                                                           ',	5000,	10),
(6,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	53165.55,	35,	567.42,	1.01,	'🟡Тинькофф                                                                                                                                                                                                                                                      ',	1985.77,	NULL,	NULL,	'cancle                                                                                                                                                                                                                                                         ',	'2024-01-23 22:50:03.832041',	'71ed42d6-edf9-4198-a045-f56d4b9c1b40                                                                                                                                                                                                                           ',	20000,	10),
(8,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	53211.4,	35,	567.42,	1.01,	'🟡Тинькофф                                                                                                                                                                                                                                                      ',	2031.62,	NULL,	NULL,	'cancle                                                                                                                                                                                                                                                         ',	'2024-01-23 22:55:52.803591',	'7a916f1f-f505-4b61-a426-d3c3366170a7                                                                                                                                                                                                                           ',	20000,	10),
(11,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52271.53,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1091.75,	NULL,	NULL,	'cancle                                                                                                                                                                                                                                                         ',	'2024-01-23 23:33:26.920401',	'a57d91d0-c15b-412a-bbba-9247a44fb020                                                                                                                                                                                                                           ',	20000,	10),
(10,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52271.53,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1091.75,	NULL,	NULL,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-23 23:29:30.682191',	'918998c4-7fc0-440a-ad77-3e162aba1564                                                                                                                                                                                                                           ',	20000,	10),
(12,	'ssk1722                                                                                                                                                                                                                                                        ',	194219.56,	201407.31,	35,	2153.26,	1.01,	'🟡Тинькофф                                                                                                                                                                                                                                                      ',	7187.75,	NULL,	NULL,	'cancle                                                                                                                                                                                                                                                         ',	'2024-01-23 23:37:09.421766',	'ab8a6161-9b03-43dd-a201-2efb12740618                                                                                                                                                                                                                           ',	75897,	10),
(14,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52437.72,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1257.94,	NULL,	NULL,	'cancle                                                                                                                                                                                                                                                         ',	'2024-01-24 00:47:54.398991',	'c356f45d-92a6-4c18-9a60-1ac92473bde2                                                                                                                                                                                                                           ',	20000,	10),
(13,	'ssk1722                                                                                                                                                                                                                                                        ',	17912.92,	18272.97,	35,	198.6,	1.01,	'💵Другие банки                                                                                                                                                                                                                                                  ',	360.05,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-23 23:38:11.252804',	'aeec5496-d5d1-464b-9990-8025d36480a0                                                                                                                                                                                                                           ',	7000,	10),
(15,	'ssk1722                                                                                                                                                                                                                                                        ',	17912.92,	18349.19,	35,	198.6,	1.01,	'🟢СБП                                                                                                                                                                                                                                                           ',	436.27,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-01-24 00:59:47.581206',	'c034d8f3-81c5-4a4f-8c34-2c4bc1c1e9e8                                                                                                                                                                                                                           ',	7000,	10),
(16,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52437.72,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1257.94,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-24 01:19:06.179696',	'b08aa00a-f15f-44fb-8c49-deea3d024fd4                                                                                                                                                                                                                           ',	20000,	10),
(19,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52300.18,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1120.4,	'Круто',	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-24 01:23:04.303212',	'cb293dee-b5bd-4044-bc95-c1f700c145b6                                                                                                                                                                                                                           ',	20000,	10),
(17,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	12.79,	13.08,	35,	0.14,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	0.29,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-24 01:19:58.472858',	'2caf82af-fedb-433b-9eac-7723288bdf61                                                                                                                                                                                                                           ',	5,	10),
(18,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52300.18,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1120.4,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-24 01:21:53.044368',	'9539d1c4-590a-496a-8b1e-6e95e7dce70a                                                                                                                                                                                                                           ',	20000,	10),
(20,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52294.45,	35,	567.42,	1.01,	'🟢СБП                                                                                                                                                                                                                                                           ',	1114.67,	'Кайф',	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-24 01:24:47.030599',	'4e5655e9-69ad-46ab-913c-403a0e919ac3                                                                                                                                                                                                                           ',	20000,	10),
(21,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	52294.45,	35,	567.42,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1114.67,	NULL,	NULL,	'cancle                                                                                                                                                                                                                                                         ',	'2024-01-24 01:25:19.913553',	'a1878582-6d35-4e24-886c-6e9b975fea61                                                                                                                                                                                                                           ',	20000,	10),
(22,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	53091.57,	2.56,	573.86,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1911.79,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-01-24 02:52:33.353703',	'f75433df-6404-4088-a8a6-f8c27cade7f5                                                                                                                                                                                                                           ',	20000,	10),
(23,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	51179.78,	53091.57,	2.56,	573.86,	1.01,	'🟢Сбербанк                                                                                                                                                                                                                                                      ',	1911.79,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-01-24 02:55:06.131139',	'ccd94c99-700c-4a32-b55a-170aacf482e1                                                                                                                                                                                                                           ',	20000,	10),
(24,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25589.89,	26900,	2.69,	288.1,	1.025,	'🟢Сбербанк 93.22                                                                                                                                                                                                                                                ',	1310.11,	NULL,	NULL,	'progress                                                                                                                                                                                                                                                       ',	'2024-01-26 01:07:25.356002',	'6f5e94c5-26a8-480d-a3cc-792f6804b5a9                                                                                                                                                                                                                           ',	10000,	10),
(25,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25589.89,	26900,	2.69,	288.1,	1.025,	'🟢Сбербанк 93.22                                                                                                                                                                                                                                                ',	1310.11,	NULL,	NULL,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-26 01:08:05.005498',	'516eafb5-6025-46f5-8a80-719c61371087                                                                                                                                                                                                                           ',	10000,	10),
(26,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	17912.92,	18830,	2.69,	201.67,	1.025,	'🟢Сбербанк 93.22                                                                                                                                                                                                                                                ',	917.08,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-26 01:21:52.239178',	'f450b620-079d-4bec-b08a-bab61d2a545b                                                                                                                                                                                                                           ',	7000,	10),
(27,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	17912.92,	18830,	2.69,	201.67,	1.025,	'🟢Сбербанк 93.22                                                                                                                                                                                                                                                ',	917.08,	NULL,	NULL,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-26 01:24:12.445036',	'842f1dc9-74d6-4d02-a365-814d627e90af                                                                                                                                                                                                                           ',	7000,	10),
(28,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	4.187462e+07,	1.309099e+06,	0.08,	471441.56,	1.025,	'🟡 Тинькофф 2.76                                                                                                                                                                                                                                                ',	-4.056552e+07,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-26 01:25:21.16668',	'3800a914-7c6e-48cd-9931-4ce1a427d7dc                                                                                                                                                                                                                           ',	1.6363737e+07,	10),
(31,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25635.2,	27200,	2.72,	285.63,	1.03,	'🟢Сбербанк 95.33                                                                                                                                                                                                                                                ',	1564.8,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-14 15:45:22.588544',	'04412c2e-c481-4fd0-87dd-917facc74d6c                                                                                                                                                                                                                           ',	10000,	10),
(29,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25589.89,	26900,	2.69,	288.1,	1.025,	'🟠 Райффайзенбанк 93.33                                                                                                                                                                                                                                         ',	1310.11,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-26 01:29:13.012916',	'9ebd39c0-d066-4df0-8dec-4b111ff2b4a4                                                                                                                                                                                                                           ',	10000,	10),
(32,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25650.84,	27300,	2.73,	285.8,	1.03,	'🟢Сбербанк 95.38                                                                                                                                                                                                                                                ',	26346.92,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-14 16:06:19.426893',	'62ba1f8e-d91f-41ad-afcf-19447f14b175                                                                                                                                                                                                                           ',	10000,	10),
(33,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25682.57,	27300,	2.73,	285.8,	1.03,	'🟢Сбербанк 95.38                                                                                                                                                                                                                                                ',	771.0248,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-14 16:10:49.611637',	'f4431174-5357-438b-89a6-1416b93c91c2                                                                                                                                                                                                                           ',	10000,	10),
(30,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25589.89,	28300,	2.83,	295.68,	1.025,	'💵 Наличные 95.66                                                                                                                                                                                                                                               ',	2710.11,	NULL,	5,	'complete                                                                                                                                                                                                                                                       ',	'2024-01-26 03:34:05.950907',	'696fb075-d272-4433-8a82-3e0ffa7cdc30                                                                                                                                                                                                                           ',	10000,	10),
(34,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25663.15,	27300,	2.73,	285.8,	1.03,	'🟢Сбербанк 95.38                                                                                                                                                                                                                                                ',	770.4417,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-14 16:15:06.869132',	'413c4d06-0aec-4b5b-9eef-e33a5811a465                                                                                                                                                                                                                           ',	10000,	10),
(35,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25660.92,	27300,	2.73,	285.65,	1.03,	'🟩 USDT                                                                                                                                                                                                                                                         ',	789.878,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-14 21:15:30.97004',	'63b7ea86-576a-4b2c-b230-9c8ccb8be348                                                                                                                                                                                                                           ',	10000,	10),
(36,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25660.92,	27200,	2.72,	285.71,	1.03,	'🟢Сбербанк 95.28                                                                                                                                                                                                                                                ',	1539.08,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-14 21:15:35.439944',	'12dbd2b2-e837-4860-8381-77be15730599                                                                                                                                                                                                                           ',	10000,	10),
(37,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	25660.92,	27300,	2.73,	285.65,	1.03,	'🟩 USDT                                                                                                                                                                                                                                                         ',	789.878,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-14 21:17:59.304238',	'eb19a90a-3f9d-49f0-b7a3-f5a107955207                                                                                                                                                                                                                           ',	10000,	10),
(38,	'NEVINOVEN700                                                                                                                                                                                                                                                   ',	25793.28,	27400,	2.74,	286.45,	1.03,	'🟩 USDT                                                                                                                                                                                                                                                         ',	798.338,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-15 14:43:57.071115',	'44b7b5f7-2793-4ac1-977f-b77537143c2b                                                                                                                                                                                                                           ',	10000,	10),
(39,	'Unknow                                                                                                                                                                                                                                                         ',	25674.78,	27300,	2.73,	285.06,	1.03,	'🟢Сбербанк 95.7                                                                                                                                                                                                                                                 ',	1625.22,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-15 15:44:06.248499',	'535c7f61-3338-4f7b-8fb1-9418f4a8201c                                                                                                                                                                                                                           ',	10000,	10),
(40,	'Unknow                                                                                                                                                                                                                                                         ',	0,	0,	283.77,	283.77,	1.03,	'🟩 USDT                                                                                                                                                                                                                                                         ',	0,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-15 15:50:25.858326',	'4df42d35-620c-4816-9e65-433f72023772                                                                                                                                                                                                                           ',	10000,	10),
(41,	'Unknow                                                                                                                                                                                                                                                         ',	38329.85,	40650,	2.71,	425.65,	1.03,	'🟡 Тинькофф 95.53                                                                                                                                                                                                                                               ',	2320.15,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-15 15:50:45.157914',	'ce327818-e80d-46ea-a141-ee15308af2b5                                                                                                                                                                                                                           ',	15000,	10),
(42,	'NEVINOVEN700                                                                                                                                                                                                                                                   ',	25553.23,	27100,	2.71,	283.77,	1.03,	'🟡 Тинькофф 95.53                                                                                                                                                                                                                                               ',	1546.77,	NULL,	NULL,	'request                                                                                                                                                                                                                                                        ',	'2024-02-15 15:53:21.365973',	'7438188b-4918-4ba6-8530-2c911c3d4bf7                                                                                                                                                                                                                           ',	10000,	10);

DROP TABLE IF EXISTS "state_data";
DROP SEQUENCE IF EXISTS state_data_id_seq;
CREATE SEQUENCE state_data_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."state_data" (
    "id" integer DEFAULT nextval('state_data_id_seq') NOT NULL,
    "text" text NOT NULL,
    "type" character(255) NOT NULL,
    "admin" boolean DEFAULT false NOT NULL,
    CONSTRAINT "state_data_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "state_data" ("id", "text", "type", "admin") VALUES
(1,	'Вас приветствует обменник 4exchange 💸

Честный, быстрый, надёжный партнер в сфере конвертации и обмена любой популярной валюты и криптовалюты 🔐

Совершите обмен в 4 шага:
1️⃣ Автоматический расчет курса внутри бота
2️⃣ Утверждение сделки с оператором
3️⃣ Доставка курьера
4️⃣ Честный обмен

Вы можете оплатить любым удобным Вам способом и получить тайские баты:

🛵 Курьерской доставкой в Паттайя
💳 На тайскую карту
🏧 В любом ближайшем банкомате
💰 Оплатить недвижимость, транспорт, оформить документы и банковские счета

PS: Курс рассчитывается автоматически и зависит от способа оплаты и объема обмена, а также биржевого курса, поэтому можете мониторить курс в течении дня. Не стесняйтесь пользоваться ботом, менять способы оплаты и размещать заказы, ведь обмен можно отменить на любом этапе, до утверждения сделки с оператором. Подробнее о процессе вы можете узнать на кнопке информации ⤵️
А также ознакомиться с нашими отзывами ⤵️',	'logo                                                                                                                                                                                                                                                           ',	'f'),
(2,	'https://t.me/channel4exchange_thai/20',	'review_link                                                                                                                                                                                                                                                    ',	'f'),
(3,	'🤖 **Наш бот помогает подобрать для Вас наилучший курс в зависимости от объема, способа платежа и курса на бирже, в режиме реального времени, который автоматически обновляется ежеминутно** ⏳
*помните, что курс является приблизительным и согласовывается с оператором*

Если у Вас есть особые пожелания по сделке, времени и месту, а также по другим вопросам, Вы всегда можете обратиться к нашему оператору @operator4exchange

При заказе доставки наличных в Паттайя Вам необходимо сделать всего **4️⃣ шага** !

1️⃣ Разместить заказ внутри бота
2️⃣ Утвердить курс, время и место с оператором
3️⃣ Совершить обмен, перечислив оплату при личной встрече, и сразу забрать баты
4️⃣ Помочь нам в дальнейшем сотрудничестве, поставив отзыв


При желании оформления банковских счетов/оплаты зарубежных сервисов, недвижимости/оплаты сделки наличными рублями и доллорами, уточняйте актуальную информацию у опертора 🔔


А также, представляем Вам уникальное предложение: получайте наличные по всему Таиланду в банкоматах, даже не имея банковской карты!
🏧 Этот сервис предлагает возможность вывести деньги практически из любой точки страны, будь то аэропорт или отдаленный остров. Вот инструкция по использованию каждого из банкоматов:

🟦 [Bangkok Bank ATM - Синий банкомат](https://t.me/channel4exchange_thai/21)

🟨 [Krungsri Bank ATM - Желтый банкомат](https://t.me/channel4exchange_thai/22)

🟩 [Kasikorn Bank ATM - Зеленый банкомат](https://t.me/channel4exchange_thai/23)

🔹 [KrungThai Bank - Голубой банкомат](https://t.me/channel4exchange_thai/24)


Чтобы быстрее найти ближайший банкомат или сообщить курьеру свое местоположение, поделитесь с ботом геолокацией (не переживайте, мы не храним данную информацию, и о ней узнает только оператор-курьер) 📍

Это не сложно, на всех этапах оператор будет с Вами !

С уважением, команда 4EXCHANGE 🙌',	'info                                                                                                                                                                                                                                                           ',	'f'),
(4,	'Введите сумму, которая необходима для обмена в батах или выберите при помощи кнопок ⏬',	'hello_message                                                                                                                                                                                                                                                  ',	'f'),
(5,	'Привет, админ!',	'hello_message                                                                                                                                                                                                                                                  ',	't');

DROP TABLE IF EXISTS "user_marje";
DROP SEQUENCE IF EXISTS user_marje_id_seq;
CREATE SEQUENCE user_marje_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."user_marje" (
    "id" integer DEFAULT nextval('user_marje_id_seq') NOT NULL,
    "count" integer NOT NULL,
    "marje" integer NOT NULL,
    CONSTRAINT "user_marje_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "user_state";
DROP SEQUENCE IF EXISTS state_id_seq;
CREATE SEQUENCE state_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."user_state" (
    "id" integer DEFAULT nextval('state_id_seq') NOT NULL,
    "chat_id" character(255) NOT NULL,
    "state" character(255),
    "bat" character(255),
    "complete" character(255),
    CONSTRAINT "chat_id_unique_idx" UNIQUE ("chat_id"),
    CONSTRAINT "state_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "user_state" ("id", "chat_id", "state", "bat", "complete") VALUES
(10,	'6908096537                                                                                                                                                                                                                                                     ',	'ожидание_выбора_способа_оплаты                                                                                                                                                                                                                                 ',	'0                                                                                                                                                                                                                                                              ',	NULL),
(1,	'1194700554                                                                                                                                                                                                                                                     ',	'0                                                                                                                                                                                                                                                              ',	'0                                                                                                                                                                                                                                                              ',	NULL);

DROP TABLE IF EXISTS "users";
DROP SEQUENCE IF EXISTS users_id_seq;
CREATE SEQUENCE users_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."users" (
    "id" integer DEFAULT nextval('users_id_seq') NOT NULL,
    "name" character(255) NOT NULL,
    "chat_id" character(255) NOT NULL,
    "request" boolean DEFAULT false NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "users" ("id", "name", "chat_id", "request") VALUES
(4,	'ssk1722                                                                                                                                                                                                                                                        ',	'747612773                                                                                                                                                                                                                                                      ',	't'),
(3,	'Summer_Death                                                                                                                                                                                                                                                   ',	'1194700554                                                                                                                                                                                                                                                     ',	'f'),
(5,	'operator4exchange                                                                                                                                                                                                                                              ',	'6920037183                                                                                                                                                                                                                                                     ',	'f'),
(6,	'OxranaTrudaOnline                                                                                                                                                                                                                                              ',	'5480919609                                                                                                                                                                                                                                                     ',	't'),
(8,	'Xd                                                                                                                                                                                                                                                             ',	'6908096537                                                                                                                                                                                                                                                     ',	't'),
(7,	'NEVINOVEN700                                                                                                                                                                                                                                                   ',	'5794240411                                                                                                                                                                                                                                                     ',	't');

-- 2024-02-29 15:27:01.250709+00
